language: python
branches:
  only:
    - master
python:
  - '2.6'
  - '2.7'
  - '3.5'
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: python setup.py flake8
deploy:
  provider: pypi
  user: apslite
  password:
    secure: cqTKvKs2blXg6xkHMp80rDejP1CH22QVOCpCt6tS1i6i9ONj02tliLi+1h9wD1ZXwlRW4i8RwYtVE2vtbltIqkDyTPrZUZQn06NaUjBiyKyICJa4QEpAfGFjXknW7GG0mLszNUPTQHXSuaZOKM5RhtBKVghf+1GhC1hgNPddVo7cNcyZD6AD3hBmf+jPhPrR6GA5TVQCUN0YyUXBhi7+k5Brp8uxbmP5oRjuyCT0QV0D1sKPB1B07yrD87BfjsM3CJwM24mbrtIAL3hd+sXSrhGYNQrirEYKWcYiJuDn6TwZciqy+lWNfD7MPLYHSLOg+nZdD/KVJLN5SK7GKedzl6kxtMwD2VK/5r9KoWDwsnDx6YpKs5Y4yq/GQG5UXpn5+LojXIeaY4XFSqoK716X0JdlJ16ReV0xwdv/WyF+BgUjjwc+RYQHhVFHSq3Df1UHdvGUvcCtfEYGPwi4PHZNXu7+HJe0xwzP4k8FgKA9PuWKEceESEQZpJ8+zftqbdq0JA1KLduqRbvxYdqMK+cguw7dOsSOcAwFnN9hlhzClgoSapdVd+D1u5996VucBsOu9b9KC+5ebUhsZdEqLuNkXuCDWrf+2j4ILU4HZvDQgiyZRFPWbtp6acrCudrFokhOOsFGvK9SKWwjBz+nydDnCZlgbpC1baGxX1kl1k2bvkA=
  on:
    distributions: sdist bdist_wheel